# Generated by Django 3.2.5 on 2022-01-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empty_person',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gtree_db.person')),
            ],
            options={
                'managed': False,
            },
            bases=('gtree_db.person',),
        ),
    ]
