# Generated by Django 3.2.5 on 2021-08-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('comments', models.TextField(blank=True, null=True)),
                ('creating_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('first_name', models.CharField(max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=60, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('death_date', models.DateTimeField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creating_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_name', to='gtree_db.person')),
                ('mainPhoto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_mainPhoto', to='gtree_db.photo')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_name', to='gtree_db.person')),
                ('pers_photo', models.ManyToManyField(blank=True, related_name='to_pers_photo', to='gtree_db.Photo')),
                ('who_married', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='married_name', to='gtree_db.person')),
            ],
        ),
    ]
