# Generated by Django 3.2.5 on 2021-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'birth_date'), name='unicue_person'),
        ),
    ]
