# Generated by Django 3.2.5 on 2021-08-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0002_person_unicue_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mainPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
