# Generated by Django 3.2.5 on 2021-08-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0003_alter_person_mainphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Женский'), ('M', 'Мужской')], max_length=1, null=True),
        ),
    ]
