# Generated by Django 3.2.5 on 2021-08-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0004_alter_person_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='previous_last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
