# Generated by Django 3.2.5 on 2021-08-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0007_auto_20210821_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата смерти, если была'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=45, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mainPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='previous_last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Предыдущая фамилия, если была'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Женский'), ('M', 'Мужской')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Служебные картинки'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Имя служебных картинок'),
        ),
    ]
