# Generated by Django 3.2.5 on 2021-08-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0008_auto_20210821_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_name', to='gtree_db.person', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mainPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='gtree_db/static/img/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_name', to='gtree_db.person', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pers_photo',
            field=models.ManyToManyField(blank=True, related_name='to_pers_photo', to='gtree_db.Photo', verbose_name='На фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='who_married',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='married_name', to='gtree_db.person', verbose_name='Муж/Жена'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gtree_db/static/img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='gtree_db/static/img/', verbose_name='Служебные картинки'),
        ),
    ]
