# Generated by Django 3.2.5 on 2021-08-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0009_auto_20210821_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mainPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/work/', verbose_name='Служебные картинки'),
        ),
    ]
