# Generated by Django 3.2.5 on 2021-08-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0010_auto_20210825_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mainPhoto',
            field=models.ImageField(default='work/Without photo.jpg', upload_to='img/', verbose_name='Главное фото'),
        ),
    ]
