# Generated by Django 3.2.5 on 2021-10-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0012_empty_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mainPhotofile',
            field=models.BinaryField(blank=True, max_length=6000000, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='Photofile',
            field=models.BinaryField(blank=True, max_length=6000000, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='picturefile',
            field=models.BinaryField(blank=True, max_length=6000000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти, если была'),
        ),
    ]
