# Generated by Django 3.2.5 on 2021-10-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0013_auto_20211002_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mainPhotofile',
            field=models.BinaryField(blank=True, editable=True, help_text='Максимум 5 мегабайт', max_length=6000000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pers_photo',
            field=models.ManyToManyField(blank=True, help_text='фото крупным планом', related_name='to_pers_photo', to='gtree_db.Photo', verbose_name='На фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Photofile',
            field=models.BinaryField(blank=True, help_text='Максимум 5 мегабайт', max_length=6000000, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picturefile',
            field=models.BinaryField(blank=True, help_text='Максимум 5 мегабайт', max_length=6000000, null=True),
        ),
    ]
