# Generated by Django 3.2.5 on 2021-10-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0014_auto_20211016_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Photofile',
            new_name='photofile',
        ),
    ]
