# Generated by Django 3.2.5 on 2021-11-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0015_rename_photofile_photo_photofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_name', to='gtree_db.person', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_name', to='gtree_db.person', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='person',
            name='who_married',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='married_name', to='gtree_db.person', verbose_name='Муж/Жена'),
        ),
    ]
