# Generated by Django 3.2.5 on 2021-12-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0016_auto_20211119_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='father_name', to='gtree_db.person', verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mother_name', to='gtree_db.person', verbose_name='Мать'),
        ),
        migrations.AlterField(
            model_name='person',
            name='who_married',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='married_name', to='gtree_db.person', verbose_name='Муж/Жена'),
        ),
    ]
