# Generated by Django 3.2.5 on 2022-01-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0017_auto_20211227_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photofile',
            new_name='photo_file',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='the_photo',
        ),
    ]
