# Generated by Django 3.2.5 on 2022-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0018_auto_20220101_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arch_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_photo', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Фото')),
                ('photo_file', models.BinaryField(blank=True, help_text='Максимум 5 мегабайт', max_length=6000000, null=True)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('creating_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
