# Generated by Django 3.2.5 on 2022-05-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0019_arch_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arch_Photo',
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
    ]
