# Generated by Django 3.2.5 on 2022-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtree_db', '0020_auto_20220525_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Фамилия'),
        ),
    ]
